#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// FORWARD DECLARATIONS


namespace BaseHumanAnimBP_Fists { struct FAnimBlueprintGeneratedConstantData; }

namespace FPVMeleeWeaponAnimBP_Base { struct FAnimBlueprintGeneratedConstantData; }

namespace SK_Male_FacialHair_Viking_Long_AnimBP { struct FAnimBlueprintGeneratedConstantData; }

namespace OptionsMenu { class UOptionsMenu_C; }

namespace SK_Male_Hair_FDefault_Long_AnimBP { struct FAnimBlueprintGeneratedConstantData; }

namespace Female_Hair_Default_Long_AnimBP { struct FAnimBlueprintGeneratedConstantData; }

namespace SK_Male_Hair_Afro_Mid_AnimBP { struct FAnimBlueprintGeneratedConstantData; }

namespace SK_Female_FacialHair_DreadBeard_Mid_AnimBP { struct FAnimBlueprintGeneratedConstantData; }

namespace OptionsMenu_PC { class UOptionsMenu_C; }

namespace SK_Male_Hair_Mohawk_animBP { struct FAnimBlueprintGeneratedConstantData; }

namespace Female_Hair_Ponytail_Short_AnimBP { struct FAnimBlueprintGeneratedConstantData; }

namespace Rockwell_Anime_AnimBP { struct FAnimBlueprintGeneratedConstantData; }

namespace SK_RebelMeiYin_Anime_Skeleton_AnimBP { struct FAnimBlueprintGeneratedConstantData; }

namespace Shastasaurus_AnimBP { struct FAnimBlueprintGeneratedConstantData; }

namespace Female_Hair_Romantic_Mid_AnimBP { struct FAnimBlueprintGeneratedConstantData; }

namespace TPV_ClimbPick_MaleAnimBP { struct FAnimBlueprintGeneratedConstantData; }

namespace Female_Hair_Mohawk_Short_AnimBP { struct FAnimBlueprintGeneratedConstantData; }

namespace TPV_Hatchet_MaleAnimBP { struct FAnimBlueprintGeneratedConstantData; }

namespace SK_Male_Viking_Hair_Short_AnimBP { struct FAnimBlueprintGeneratedConstantData; }

namespace SK_Female_Hair_MDefault_Long_AnimBP { struct FAnimBlueprintGeneratedConstantData; }

namespace SK_Female_Hair_Afro_Short_AnimBP { struct FAnimBlueprintGeneratedConstantData; }

namespace SK_Male_FacialHair_Viking_Short_AnimBP { struct FAnimBlueprintGeneratedConstantData; }

namespace SK_Female_FacialHair_DreadBeard_Long_AnimBP { struct FAnimBlueprintGeneratedConstantData; }

namespace EngramEntry_Glowstick { class UEngramEntry_Glowstick_C; }

namespace SK_Male_Hair_Braids_Mid_AnimBP { struct FAnimBlueprintGeneratedConstantData; }

namespace SK_Female_Hair_Braids_Long_AnimBP { struct FAnimBlueprintGeneratedConstantData; }

namespace TPV_Lance_MaleAnimBP { struct FAnimBlueprintGeneratedConstantData; }

namespace Human_M_Hair_Ponytail_Mid_AnimBP { struct FAnimBlueprintGeneratedConstantData; }

namespace SK_Female_Hair_Bang_Mid_AnimBP { struct FAnimBlueprintGeneratedConstantData; }

namespace SK_Male_Viking_Hair_Long_AnimBP { struct FAnimBlueprintGeneratedConstantData; }

namespace SK_Male_Hair_Dreadlocks_Mid_AnimBP { struct FAnimBlueprintGeneratedConstantData; }

namespace SK_Female_FacialHair_DreadBeard_Short_AnimBP { struct FAnimBlueprintGeneratedConstantData; }

namespace SK_Female_Hair_Viking_Mid_AnimBP { struct FAnimBlueprintGeneratedConstantData; }

namespace Alasie_AnimBP { struct FAnimBlueprintGeneratedConstantData; }

namespace Male_DreadBeard_Mid { struct FAnimBlueprintGeneratedConstantData; }

namespace SK_Male_Hair_Mohawk_Mid_AnimBP { struct FAnimBlueprintGeneratedConstantData; }

namespace Male_Hair_Romantic_Mid_AnimBP { struct FAnimBlueprintGeneratedConstantData; }

namespace SK_Male_FacialHair_Viking_Mid_AnimBP { struct FAnimBlueprintGeneratedConstantData; }

namespace SK_Male_Hair_Braids_Long_AnimBP { struct FAnimBlueprintGeneratedConstantData; }

namespace SK_Male_Viking_Hair_Mid_AnimBP { struct FAnimBlueprintGeneratedConstantData; }

namespace SK_Male_Hair_Dreadlocks_Long_AnimBP { struct FAnimBlueprintGeneratedConstantData; }

namespace HM_TPV_Empty_PoseLayer_AnimBP { struct FAnimBlueprintGeneratedConstantData; }

namespace Meiyin_AnimBP { struct FAnimBlueprintGeneratedConstantData; }

namespace SK_Male_Hair_Bang_Long_AnimBP { struct FAnimBlueprintGeneratedConstantData; }

namespace SK_Male_Hair_Afro_Short_AnimBP { struct FAnimBlueprintGeneratedConstantData; }

namespace Female_Hair_Mohawk_Mid_AnimBP { struct FAnimBlueprintGeneratedConstantData; }

namespace SK_Male_Hair_Dreadlocks_Short_AnimBP { struct FAnimBlueprintGeneratedConstantData; }

namespace SK_Female_Hair_Viking_Short_AnimBP { struct FAnimBlueprintGeneratedConstantData; }

namespace SK_MeiyinS2_Anime_Skeleton_AnimBP { struct FAnimBlueprintGeneratedConstantData; }

namespace Female_Hair_Romantic_Long_AnimBP { struct FAnimBlueprintGeneratedConstantData; }

namespace SK_Male_Hair_FDefault_Short_AnimBP { struct FAnimBlueprintGeneratedConstantData; }

namespace Female_Hair_Default_Mid_AnimBP { struct FAnimBlueprintGeneratedConstantData; }

namespace SK_Female_Hair_MDefault_Mid_AnimBP { struct FAnimBlueprintGeneratedConstantData; }

namespace Male_Hair_Romantic_Long_AnimBP { struct FAnimBlueprintGeneratedConstantData; }

namespace Female_Hair_Ponytail_Mid_AnimBP { struct FAnimBlueprintGeneratedConstantData; }

namespace Human_Male_TPV_GroundConform_AnimBP { struct FAnimBlueprintGeneratedConstantData; }

namespace Henry_Anime_AnimBP { struct FAnimBlueprintGeneratedConstantData; }

namespace Female_Hair_Mohawk_Long_AnimBP { struct FAnimBlueprintGeneratedConstantData; }

namespace WeaponFistsAnimBlueprint { struct FAnimBlueprintGeneratedConstantData; }

namespace Human_M_Hair_Ponytail_AnimBP { struct FAnimBlueprintGeneratedConstantData; }

namespace GPSHumanAnimBP { struct FAnimBlueprintGeneratedConstantData; }

namespace SK_Female_Hair_MDefault_Short_AnimBP { struct FAnimBlueprintGeneratedConstantData; }

namespace SK_Female_Hair_Braids_Mid_AnimBP { struct FAnimBlueprintGeneratedConstantData; }

namespace Female_Hair_Romantic_Short_AnimBP { struct FAnimBlueprintGeneratedConstantData; }

namespace SK_Female_Hair_Viking_Long_AnimBP { struct FAnimBlueprintGeneratedConstantData; }

namespace HM_TPV_ClimbPick_AnimBP { struct FAnimBlueprintGeneratedConstantData; }

namespace SK_Male_Hair_Default_Mid_AnimBP { struct FAnimBlueprintGeneratedConstantData; }

namespace SK_Female_Hair_Afro_Long_AnimBP { struct FAnimBlueprintGeneratedConstantData; }

namespace EngramEntry_GlowStick { class UEngramEntry_Glowstick_C; }

namespace Male_DreadBeard_Short_AnimBP { struct FAnimBlueprintGeneratedConstantData; }

namespace Male_Hair_Romantic_Short_AnimBP { struct FAnimBlueprintGeneratedConstantData; }

namespace SimpleHumanTPoseAnimBP { struct FAnimBlueprintGeneratedConstantData; }

namespace SK_Male_Hair_Default_short_AnimBP { struct FAnimBlueprintGeneratedConstantData; }

namespace Shastasaurus_GroundConform_AnimBP { struct FAnimBlueprintGeneratedConstantData; }

namespace Human_Male_TPV_PPAnimBP { struct FAnimBlueprintGeneratedConstantData; }

namespace SK_Female_Hair_Bang_Long_AnimBP { struct FAnimBlueprintGeneratedConstantData; }

namespace BaseHumanAnimBP_Fists_Female { struct FAnimBlueprintGeneratedConstantData; }

namespace SK_Female_Hair_Afro_Mid_AnimBP { struct FAnimBlueprintGeneratedConstantData; }

namespace Female_Hair_Ponytail_Long_AnimBP { struct FAnimBlueprintGeneratedConstantData; }

namespace John_Anime_AnimBP { struct FAnimBlueprintGeneratedConstantData; }

namespace SK_Female_Hair_Bang_Short_AnimBP { struct FAnimBlueprintGeneratedConstantData; }

namespace Female_Hair_Default_Short_AnimBP { struct FAnimBlueprintGeneratedConstantData; }

namespace SK_Male_Hair_Bang_Skeleton_Mid_AnimBP { struct FAnimBlueprintGeneratedConstantData; }

namespace SK_Female_Hair_Dreadlocks_Long_AnimBP { struct FAnimBlueprintGeneratedConstantData; }

namespace SK_Male_FacialHair_DreadBeard_Long_AnimBP { struct FAnimBlueprintGeneratedConstantData; }

namespace SK_Male_Hair_Bang_Short_AnimBP { struct FAnimBlueprintGeneratedConstantData; }

namespace SK_Male_Hair_Braids_Short_AnimBP { struct FAnimBlueprintGeneratedConstantData; }

namespace Shastasaurus_PPAnimBP { struct FAnimBlueprintGeneratedConstantData; }

namespace SK_Male_Hair_Afro_Long_AnimBP { struct FAnimBlueprintGeneratedConstantData; }

namespace SK_Male_Hair_Default_long_AnimBP { struct FAnimBlueprintGeneratedConstantData; }

namespace SK_Male_Hair_FDefault_Mid_AnimBP { struct FAnimBlueprintGeneratedConstantData; }

namespace SK_Helena_Anime_Skeleton_AnimBP { struct FAnimBlueprintGeneratedConstantData; }

namespace SK_Chava_Anime_Skeleton_AnimBP { struct FAnimBlueprintGeneratedConstantData; }

namespace Ptero_GroundConform_AnimBP { struct FAnimBlueprintGeneratedConstantData; }

namespace SimpleHumanTPoseAnimBP_Rotated { struct FAnimBlueprintGeneratedConstantData; }


namespace Human_Male_TPV_Twist_CtrlRig
{
	class URigVMMemory_Literal;
	class URigVMMemory_Work;
}

namespace Human_Male_TPV_OrientationWarping_CtrlRig
{
	class URigVMMemory_Work;
	class URigVMMemory_Literal;
}

namespace BaseHumanAnimBP
{
	struct FAnimBlueprintGeneratedMutableData;
	struct FAnimBlueprintGeneratedConstantData;
}

namespace OnlineSubsystemUtils
{
	class UOnlineEngineInterfaceImpl;
	//class UOnlineEngineInterfaceImpl;
}

namespace FPVMeleeWeaponAnimBP_Lance
{
	struct FAnimBlueprintGeneratedMutableData;
	struct FAnimBlueprintGeneratedConstantData;
}

namespace Human_WeaponIK_CtrlRig
{
	class URigVMMemory_Work;
	class URigVMMemory_Literal;
}

namespace FPVClimbPickWeaponAnimBP_Base
{
	struct FAnimBlueprintGeneratedConstantData;
	struct FAnimBlueprintGeneratedMutableData;
}

namespace Human_GroundConform_CtrlRig
{
	class URigVMMemory_Work;
	class URigVMMemory_Literal;
}

namespace TrainEngine_AnimBP
{
	struct FAnimBlueprintGeneratedConstantData;
	struct FAnimBlueprintGeneratedMutableData;
}

namespace Male_Hair_Afro_Mid_CtrlRig
{
	class URigVMMemory_Work;
	class URigVMMemory_Literal;
}

namespace Human_AlternateIK_CtrlRig
{
	class URigVMMemory_Literal;
	class URigVMMemory_Work;
}

namespace Human_ModifyPose_CtrlRig
{
	class URigVMMemory_Literal;
	class URigVMMemory_Work;
}

namespace Kor_Anime_AnimBP
{
	struct FAnimBlueprintGeneratedConstantData;
	struct FAnimBlueprintGeneratedMutableData;
}

namespace SK_Chava_Anime_Skeleton_CtrlRig
{
	class URigVMMemory_Work;
	class URigVMMemory_Literal;
}

namespace Male_DreadBeard_Long_CtrlRig
{
	class URigVMMemory_Literal;
	class URigVMMemory_Work;
}

namespace Human_Male_TPV_LegIK_CtrlRig
{
	class URigVMMemory_Work;
	class URigVMMemory_Literal;
}

namespace Male_DreadBeard_Short_CtrlRig
{
	class URigVMMemory_Work;
	class URigVMMemory_Literal;
}

namespace Female_Hair_Afro_Mid_CtrlRig
{
	class URigVMMemory_Work;
	class URigVMMemory_Literal;
}

namespace Female_Hair_Mohawk_Long_CtrlRig
{
	class URigVMMemory_Literal;
	class URigVMMemory_Work;
}

namespace Kor_Anime_CtrlRig
{
	class URigVMMemory_Work;
	class URigVMMemory_Literal;
}

namespace Gladiatrix_Anime_AnimBP
{
	struct FAnimBlueprintGeneratedMutableData;
	struct FAnimBlueprintGeneratedConstantData;
}

namespace Rockwell_Anime_CtrlRig
{
	class URigVMMemory_Literal;
	class URigVMMemory_Work;
}

namespace SK_MeiYinS2_CtrlRig
{
	class URigVMMemory_Work;
	class URigVMMemory_Literal;
}

namespace Ptero_GroundConform_CtrlRig
{
	class URigVMMemory_Work;
	class URigVMMemory_Literal;
}

namespace Male_DreadBeard_Mid_CtrlRig
{
	class URigVMMemory_Literal;
	class URigVMMemory_Work;
}

namespace SK_RebelMeiYin_CtrlRig
{
	class URigVMMemory_Literal;
	class URigVMMemory_Work;
}

namespace Female_Hair_Mohawk_Mid_CtrlRig
{
	class URigVMMemory_Work;
	class URigVMMemory_Literal;
}

namespace Male_Hair_Afro_Long_CtrlRig
{
	class URigVMMemory_Literal;
	class URigVMMemory_Work;
}

namespace Shastasaurus_PostProcess_CtrlRig
{
	class URigVMMemory_Literal;
	class URigVMMemory_Work;
}

namespace Female_Hair_Afro_Long_CtrlRig
{
	class URigVMMemory_Work;
	class URigVMMemory_Literal;
}

namespace Gladiatrix_Anime_CtrlRig
{
	class URigVMMemory_Work;
	class URigVMMemory_Literal;
}

namespace Henry_Anime_CtrlRig
{
	class URigVMMemory_Literal;
	class URigVMMemory_Work;
}

namespace Nerva_Anime_CtrlRig
{
	class URigVMMemory_Literal;
	class URigVMMemory_Work;
}

namespace SK_Helena_Anime_CtrlRig
{
	class URigVMMemory_Work;
	class URigVMMemory_Literal;
}

namespace Male_Hair_Mohawk_Mid_CtrlRig
{
	class URigVMMemory_Work;
	class URigVMMemory_Literal;
}

namespace SK_Male_Hair_Mohawk_CtrlRig
{
	class URigVMMemory_Work;
	class URigVMMemory_Literal;
}

namespace Nerva_Anime_AnimBP
{
	struct FAnimBlueprintGeneratedConstantData;
	struct FAnimBlueprintGeneratedMutableData;
}

namespace FPVWeaponAnimBP_Base_Carrying
{
	struct FAnimBlueprintGeneratedMutableData;
	struct FAnimBlueprintGeneratedConstantData;
}

namespace Shastasaurus_GroundConform_CtrlRig
{
	class URigVMMemory_Work;
	class URigVMMemory_Literal;
}

namespace Meiyin_Armor_CtrlRig
{
	class URigVMMemory_Work;
	class URigVMMemory_Literal;
}

namespace Human_Rider_CtrlRig
{
	class URigVMMemory_Literal;
	class URigVMMemory_Work;
}

namespace Alasie_Anime_CtrlRig
{
	class URigVMMemory_Literal;
	class URigVMMemory_Work;
}

namespace DinoBlueprintBase_RootTransform_AimPose
{
	struct FAnimBlueprintGeneratedConstantData;
	struct FAnimBlueprintGeneratedMutableData;
}
